[GLOBAL]
pants_version = "2.14.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
]

[source]
marker_filenames = ["pyproject.toml"]

[anonymous-telemetry]
enabled = false
